// lib/data.ts

// 1. Add all the new properties to the interface
export interface PlayerData {
  id: string;
  name: string;
  position: string;
  number: number;
  AGE: string;
  countryFlag: string;
  cm: number;
  lb: string;
  image: string;
  bio: string;
  dateOfBirth: string; // New
  nationality: string; // New
  preferredFoot: string; // New
  status: string; // New
}

// 2. Add the corresponding data for each player
export const playersData: PlayerData[] = [
  {
    "id": "1",
    "name": "Emeka Nwosu",
    "position": "Left Winger",
    "number": 7,
    "AGE": "25 years",
    "countryFlag": "ng",
    "cm": 172,
    "lb": "150",
    "image": "/images/avaplone.png",
    "bio": "A pacy winger with dazzling footwork, Emeka Nwosu rose through the ranks of the Nigerian youth system. Known for his ability to cut inside and deliver killer crosses, he has become a fan favorite for his relentless work rate and spectacular goals.",
    "dateOfBirth": "May 14, 2000",
    "nationality": "Nigerian",
    "preferredFoot": "Right",
    "status": "Active"
  },
  {
    "id": "2",
    "name": "Kofi Mensah",
    "position": "Centre Back",
    "number": 5,
    "AGE": "29 years",
    "countryFlag": "gh",
    "cm": 185,
    "lb": "180",
    "image": "/images/avaptwo.png",
    "bio": "An old-school, no-nonsense defender, Kofi Mensah is a rock at the heart of the defense. His leadership qualities and aerial dominance make him an invaluable asset. He is respected for his tactical intelligence and commanding presence on the pitch.",
    "dateOfBirth": "March 2, 1996",
    "nationality": "Ghanaian",
    "preferredFoot": "Right",
    "status": "Active"
  },
  {
    "id": "3",
    "name": "Miguel Santos",
    "position": "Attacking Midfielder",
    "number": 10,
    "AGE": "27 years",
    "countryFlag": "pt",
    "cm": 177,
    "lb": "165",
    "image": "/images/avapthree.png",
    "bio": "A creative maestro from Portugal, Miguel Santos possesses exceptional vision and passing range. As the team's primary playmaker, he excels at unlocking defenses with incisive through balls and is a constant threat from set-pieces.",
    "dateOfBirth": "July 21, 1998",
    "nationality": "Portuguese",
    "preferredFoot": "Right",
    "status": "Active"
  },
  {
    "id": "4",
    "name": "Ibrahim Diallo",
    "position": "Goalkeeper",
    "number": 1,
    "AGE": "31 years",
    "countryFlag": "sn",
    "cm": 193,
    "lb": "200",
    "image": "/images/avapfour.png",
    "bio": "With incredible reflexes and a commanding penalty area presence, Ibrahim Diallo is a world-class shot-stopper. The Senegalese keeper's experience and calm demeanor provide a solid foundation for the entire team.",
    "dateOfBirth": "September 16, 1994",
    "nationality": "Senegalese",
    "preferredFoot": "Right",
    "status": "Active"
  },
  {
    "id": "5",
    "name": "Denis Ojua",
    "position": "Right Back",
    "number": 2,
    "AGE": "24 years",
    "countryFlag": "us",
    "cm": 178,
    "lb": "165",
    "image": "/images/avapsix.png",
    "bio": "A modern, athletic fullback from the USA, Denis Ojua is known for his overlapping runs and pinpoint crosses. He balances his attacking duties with solid defensive contributions, making him a key player in both phases of the game.",
    "dateOfBirth": "November 30, 2000",
    "nationality": "American",
    "preferredFoot": "Right",
    "status": "Active"
  },
  {
    "id": "6",
    "name": "Ahmed Al-Tamimi",
    "position": "Defensive Midfielder",
    "number": 6,
    "AGE": "30 years",
    "countryFlag": "eg",
    "cm": 180,
    "lb": "172",
    "image": "/images/avapfive.png",
    "bio": "The Egyptian anchor in midfield, Ahmed Al-Tamimi is a master of breaking up opposition attacks. His tireless energy, precise tackling, and ability to shield the back four are crucial to the team's defensive structure.",
    "dateOfBirth": "January 10, 1995",
    "nationality": "Egyptian",
    "preferredFoot": "Right",
    "status": "Active"
  },
   {
    "id": "7",
    "name": "Daniel Okon",
    "position": "Centre Forward",
    "number": 9,
    "AGE": "22 years",
    "countryFlag": "ng",
    "cm": 183,
    "lb": "175",
    "image": "/images/avaplone.png",
    "bio": "A prodigious young talent from Nigeria, Daniel Okon is a natural goalscorer with a powerful shot and intelligent movement. At just 22, he has already shown immense potential and is tipped for a great future in the sport.",
    "dateOfBirth": "June 5, 2003",
    "nationality": "Nigerian",
    "preferredFoot": "Right",
    "status": "Active"
  },
  {
    "id": "8",
    "name": "Samuel Akinbiyi",
    "position": "Full Back",
    "number": 3,
    "AGE": "28 years",
    "countryFlag": "ng",
    "cm": 176,
    "lb": "168",
    "image": "/images/avaptwo.png",
    "bio": "A versatile and reliable full-back, Samuel Akinbiyi is comfortable on either flank. His consistent performances and tactical discipline have made him a manager's dream, capable of shutting down opposing wingers effectively.",
    "dateOfBirth": "December 1, 1996",
    "nationality": "Nigerian",
    "preferredFoot": "Left",
    "status": "Active"
  },
  {
    "id": "9",
    "name": "Pedro Álvarez",
    "position": "Winger",
    "number": 11,
    "AGE": "26 years",
    "countryFlag": "es",
    "cm": 174,
    "lb": "160",
    "image": "/images/avapthree.png",
    "bio": "Embodying Spanish flair, Pedro Álvarez is a tricky winger who loves to take on defenders. His low center of gravity and technical skill allow him to navigate tight spaces, creating chances for himself and his teammates.",
    "dateOfBirth": "February 22, 1999",
    "nationality": "Spanish",
    "preferredFoot": "Left",
    "status": "Active"
  },
  {
    "id": "10",
    "name": "Nolan Price",
    "position": "Box-to-Box Midfielder",
    "number": 14,
    "AGE": "23 years",
    "countryFlag": "us",
    "cm": 181,
    "lb": "170",
    "image": "/images/avaptwo.png",
    "bio": "Nolan Price is the engine room of the midfield. The American international covers every blade of grass, contributing heavily in both attack and defense. His stamina and determination make him a formidable opponent.",
    "dateOfBirth": "April 18, 2002",
    "nationality": "American",
    "preferredFoot": "Right",
    "status": "Independent"
  },
  {
    "id": "11",
    "name": "Zinedine Mbaye",
    "position": "Left Back",
    "number": 13,
    "AGE": "29 years",
    "countryFlag": "sn",
    "cm": 179,
    "lb": "168",
    "image": "/images/avapseven.png",
    "bio": "Named after a legend, Zinedine Mbaye plays with elegance and strength. The Senegalese left-back is known for his powerful forward surges and solid one-on-one defending, offering a balanced threat on the flank.",
    "dateOfBirth": "August 8, 1996",
    "nationality": "Senegalese",
    "preferredFoot": "Left",
    "status": "Active"
  },
  {
    "id": "12",
    "name": "Ola Brown",
    "position": "Striker",
    "number": 19,
    "AGE": "30 years",
    "countryFlag": "ng",
    "cm": 186,
    "lb": "182",
    "image": "/images/avapsix.png",
    "bio": "A classic target man, Ola Brown uses his strength to hold up play and bring others into the game. The Nigerian striker is a dominant force in the air and a clinical finisher inside the penalty box.",
    "dateOfBirth": "October 25, 1994",
    "nationality": "Nigerian",
    "preferredFoot": "Right",
    "status": "Free Agent"
  },
  {
    "id": "13",
    "name": "Rafael Costa",
    "position": "Attacking Midfielder",
    "number": 21,
    "AGE": "28 years",
    "countryFlag": "br",
    "cm": 175,
    "lb": "163",
    "image": "/images/avaplone.png",
    "bio": "With Brazilian samba in his veins, Rafael Costa is a joy to watch. His creativity, close control, and ability to score from long range make him a constant danger to any opposition defense.",
    "dateOfBirth": "March 15, 1997",
    "nationality": "Brazilian",
    "preferredFoot": "Right",
    "status": "Active"
  },
  {
    "id": "14",
    "name": "Ismail Özkan",
    "position": "Wingback",
    "number": 22,
    "AGE": "27 years",
    "countryFlag": "tr",
    "cm": 178,
    "lb": "170",
    "image": "/images/avapsix.png",
    "bio": "A dynamic Turkish wingback, Ismail Özkan has a phenomenal engine that allows him to patrol the entire flank for 90 minutes. He is tactically astute, providing width in attack and diligence in defense.",
    "dateOfBirth": "July 12, 1998",
    "nationality": "Turkish",
    "preferredFoot": "Right",
    "status": "Active"
  },
  {
    "id": "15",
    "name": "Luka Ivanov",
    "position": "Centre Back",
    "number": 4,
    "AGE": "31 years",
    "countryFlag": "hr",
    "cm": 188,
    "lb": "185",
    "image": "/images/avapthree.png",
    "bio": "A composed and elegant ball-playing defender from Croatia, Luka Ivanov is known for his ability to start attacks from the back. His excellent reading of the game and calm distribution are his greatest strengths.",
    "dateOfBirth": "May 3, 1994",
    "nationality": "Croatian",
    "preferredFoot": "Right",
    "status": "Active"
  },
  {
    "id": "16",
    "name": "Felix Müller",
    "position": "Backup Goalkeeper",
    "number": 12,
    "AGE": "34 years",
    "countryFlag": "de",
    "cm": 192,
    "lb": "210",
    "image": "/images/avapfour.png",
    "bio": "A veteran German goalkeeper, Felix Müller brings a wealth of experience and professionalism to the squad. A reliable and vocal presence, he is an excellent mentor for the younger players and a dependable option when called upon.",
    "dateOfBirth": "January 27, 1991",
    "nationality": "German",
    "preferredFoot": "Right",
    "status": "Active"
  },
  {
    "id": "17",
    "name": "Kwaku Addo",
    "position": "Defensive Midfielder",
    "number": 8,
    "AGE": "26 years",
    "countryFlag": "gh",
    "cm": 177,
    "lb": "168",
    "image": "/images/avapseven.png",
    "bio": "Kwaku Addo is a tenacious ball-winner from Ghana who excels at breaking up play. His aggressive pressing and intelligent positioning make him a vital cog in the team's midfield, providing security for the more creative players.",
    "dateOfBirth": "August 20, 1999",
    "nationality": "Ghanaian",
    "preferredFoot": "Right",
    "status": "Active"
  },
  {
    "id": "18",
    "name": "Chinedu Eze",
    "position": "Right Winger",
    "number": 17,
    "AGE": "24 years",
    "countryFlag": "ng",
    "cm": 173,
    "lb": "160",
    "image": "/images/avaplone.png",
    "bio": "Chinedu Eze is a lightning-fast Nigerian winger who terrifies defenders with his explosive pace. He is at his best when running at fullbacks, delivering dangerous balls into the box or cutting in to unleash a powerful shot.",
    "dateOfBirth": "November 11, 2000",
    "nationality": "Nigerian",
    "preferredFoot": "Right",
    "status": "Independent"
  },
  {
    "id": "19",
    "name": "Thiago Ribeiro",
    "position": "Forward",
    "number": 9,
    "AGE": "29 years",
    "countryFlag": "br",
    "cm": 182,
    "lb": "176",
    "image": "/images/avaptwo.png",
    "bio": "A versatile Brazilian forward, Thiago Ribeiro is capable of playing anywhere across the front line. His clever movement off the ball and clinical finishing have earned him a reputation as a consistent and reliable goalscorer.",
    "dateOfBirth": "February 28, 1996",
    "nationality": "Brazilian",
    "preferredFoot": "Left",
    "status": "Active"
  },
  {
    "id": "20",
    "name": "Omar Farouk",
    "position": "Central Midfielder",
    "number": 16,
    "AGE": "25 years",
    "countryFlag": "eg",
    "cm": 176,
    "lb": "163",
    "image": "/images/avapthree.png",
    "bio": "Omar Farouk is a technically gifted Egyptian midfielder who dictates the tempo of the game. His precise passing and ability to retain possession under pressure make him the heartbeat of the team's midfield.",
    "dateOfBirth": "May 23, 2000",
    "nationality": "Egyptian",
    "preferredFoot": "Right",
    "status": "Active"
  },
  {
    "id": "21",
    "name": "Gabriel Silva",
    "position": "Left Midfielder",
    "number": 11,
    "AGE": "28 years",
    "countryFlag": "pt",
    "cm": 174,
    "lb": "162",
    "image": "/images/avapfour.png",
    "bio": "A hard-working Portuguese midfielder, Gabriel Silva provides excellent balance to the team. He combines his defensive duties with intelligent runs into the final third, contributing with both assists and crucial goals.",
    "dateOfBirth": "April 4, 1997",
    "nationality": "Portuguese",
    "preferredFoot": "Left",
    "status": "Free Agent"
  },
  {
    "id": "22",
    "name": "Brian O'Connor",
    "position": "Full Back",
    "number": 2,
    "AGE": "33 years",
    "countryFlag": "ie",
    "cm": 181,
    "lb": "175",
    "image": "/images/avapfive.png",
    "bio": "A rugged and determined Irish defender, Brian O'Connor is known for his fighting spirit and tough tackling. His experience and leadership at the back are vital, and he is a constant source of motivation for his teammates.",
    "dateOfBirth": "June 19, 1992",
    "nationality": "Irish",
    "preferredFoot": "Right",
    "status": "Active"
  },
  {
    "id": "23",
    "name": "Santiago Pérez",
    "position": "Winger",
    "number": 20,
    "AGE": "21 years",
    "countryFlag": "ar",
    "cm": 170,
    "lb": "150",
    "image": "/images/avapthree.png",
    "bio": "An exciting young Argentine winger, Santiago Pérez is a prodigious dribbler with immense talent. At just 21, he plays with a fearlessness that makes him unpredictable and a constant threat to opposition defenses.",
    "dateOfBirth": "August 1, 2004",
    "nationality": "Argentine",
    "preferredFoot": "Left",
    "status": "Active"
  },
  {
    "id": "24",
    "name": "Moses Kalu",
    "position": "Central Midfielder",
    "number": 15,
    "AGE": "32 years",
    "countryFlag": "ng",
    "cm": 179,
    "lb": "172",
    "image": "/images/avapfour.png",
    "bio": "The veteran Nigerian midfielder Moses Kalu brings composure and experience to the center of the park. His intelligent positioning and calm head under pressure are key to controlling the flow and tempo of the game.",
    "dateOfBirth": "December 12, 1992",
    "nationality": "Nigerian",
    "preferredFoot": "Right",
    "status": "Active"
  }
];

