export const playersData = [
  {
    id: "1",
    name: "Emeka Nwosu",
    position: "Left Winger",
    number: 7,
    AGE: "25 years",
    countryFlag: "ng",
    cm: 172,
    lb: "150",
    image:
      "https://ui-avatars.com/api/?name=Emeka+Nwosu&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "2",
    name: "Kofi Mensah",
    position: "Centre Back",
    number: 5,
    AGE: "29 years",
    countryFlag: "gh",
    cm: 185,
    lb: "180",
    image:
      "https://ui-avatars.com/api/?name=Kofi+Mensah&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "3",
    name: "Miguel Santos",
    position: "Attacking Midfielder",
    number: 10,
    AGE: "27 years",
    countryFlag: "pt",
    cm: 177,
    lb: "165",
    image:
      "https://ui-avatars.com/api/?name=Miguel+Santos&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "4",
    name: "Ibrahim Diallo",
    position: "Goalkeeper",
    number: 1,
    AGE: "31 years",
    countryFlag: "sn",
    cm: 193,
    lb: "200",
    image:
      "https://ui-avatars.com/api/?name=Ibrahim+Diallo&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "5",
    name: "Denis Ojua",
    position: "Right Back",
    number: 2,
    AGE: "24 years",
    countryFlag: "ng",
    cm: 178,
    lb: "165",
    image:
      "https://ui-avatars.com/api/?name=Denis+Ojua&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "6",
    name: "Ahmed Al-Tamimi",
    position: "Defensive Midfielder",
    number: 6,
    AGE: "30 years",
    countryFlag: "eg",
    cm: 180,
    lb: "172",
    image:
      "https://ui-avatars.com/api/?name=Ahmed+Al-Tamimi&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "7",
    name: "Daniel Okon",
    position: "Centre Forward",
    number: 9,
    AGE: "22 years",
    countryFlag: "ng",
    cm: 183,
    lb: "175",
    image:
      "https://ui-avatars.com/api/?name=Daniel+Okon&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "8",
    name: "Samuel Akinbiyi",
    position: "Full Back",
    number: 3,
    AGE: "28 years",
    countryFlag: "ng",
    cm: 176,
    lb: "168",
    image:
      "https://ui-avatars.com/api/?name=Samuel+Akinbiyi&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "9",
    name: "Pedro Álvarez",
    position: "Winger",
    number: 11,
    AGE: "26 years",
    countryFlag: "es",
    cm: 174,
    lb: "160",
    image:
      "https://ui-avatars.com/api/?name=Pedro+Alvarez&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "10",
    name: "Nolan Price",
    position: "Box-to-Box Midfielder",
    number: 14,
    AGE: "23 years",
    countryFlag: "us",
    cm: 181,
    lb: "170",
    image:
      "https://ui-avatars.com/api/?name=Nolan+Price&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "11",
    name: "Zinedine Mbaye",
    position: "Left Back",
    number: 13,
    AGE: "29 years",
    countryFlag: "sn",
    cm: 179,
    lb: "168",
    image:
      "https://ui-avatars.com/api/?name=Zinedine+Mbaye&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "12",
    name: "Ola Brown",
    position: "Striker",
    number: 19,
    AGE: "30 years",
    countryFlag: "ng",
    cm: 186,
    lb: "182",
    image:
      "https://ui-avatars.com/api/?name=Ola+Brown&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "13",
    name: "Rafael Costa",
    position: "Attacking Midfielder",
    number: 21,
    AGE: "28 years",
    countryFlag: "br",
    cm: 175,
    lb: "163",
    image:
      "https://ui-avatars.com/api/?name=Rafael+Costa&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "14",
    name: "Ismail Özkan",
    position: "Wingback",
    number: 22,
    AGE: "27 years",
    countryFlag: "tr",
    cm: 178,
    lb: "170",
    image:
      "https://ui-avatars.com/api/?name=Ismail+Ozkan&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "15",
    name: "Luka Ivanov",
    position: "Centre Back",
    number: 4,
    AGE: "31 years",
    countryFlag: "hr",
    cm: 188,
    lb: "185",
    image:
      "https://ui-avatars.com/api/?name=Luka+Ivanov&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "16",
    name: "Felix Müller",
    position: "Backup Goalkeeper",
    number: 12,
    AGE: "34 years",
    countryFlag: "de",
    cm: 192,
    lb: "210",
    image:
      "https://ui-avatars.com/api/?name=Felix+Muller&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "17",
    name: "Kwaku Addo",
    position: "Defensive Midfielder",
    number: 8,
    AGE: "26 years",
    countryFlag: "gh",
    cm: 177,
    lb: "168",
    image:
      "https://ui-avatars.com/api/?name=Kwaku+Addo&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "18",
    name: "Chinedu Eze",
    position: "Right Winger",
    number: 17,
    AGE: "24 years",
    countryFlag: "ng",
    cm: 173,
    lb: "160",
    image:
      "https://ui-avatars.com/api/?name=Chinedu+Eze&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "19",
    name: "Thiago Ribeiro",
    position: "Forward",
    number: 9,
    AGE: "29 years",
    countryFlag: "br",
    cm: 182,
    lb: "176",
    image:
      "https://ui-avatars.com/api/?name=Thiago+Ribeiro&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "20",
    name: "Omar Farouk",
    position: "Central Midfielder",
    number: 16,
    AGE: "25 years",
    countryFlag: "eg",
    cm: 176,
    lb: "163",
    image:
      "https://ui-avatars.com/api/?name=Omar+Farouk&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "21",
    name: "Gabriel Silva",
    position: "Left Midfielder",
    number: 11,
    AGE: "28 years",
    countryFlag: "pt",
    cm: 174,
    lb: "162",
    image:
      "https://ui-avatars.com/api/?name=Gabriel+Silva&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "22",
    name: "Brian O'Connor",
    position: "Full Back",
    number: 2,
    AGE: "33 years",
    countryFlag: "ie",
    cm: 181,
    lb: "175",
    image:
      "https://ui-avatars.com/api/?name=Brian+OConnor&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "23",
    name: "Santiago Pérez",
    position: "Winger",
    number: 20,
    AGE: "21 years",
    countryFlag: "ar",
    cm: 170,
    lb: "150",
    image:
      "https://ui-avatars.com/api/?name=Santiago+Perez&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
  {
    id: "24",
    name: "Moses Kalu",
    position: "Central Midfielder",
    number: 15,
    AGE: "32 years",
    countryFlag: "ng",
    cm: 179,
    lb: "172",
    image:
      "https://ui-avatars.com/api/?name=Moses+Kalu&size=150&background=fed7aa&color=7c2d12&bold=true",
  },
];
