// This is a placeholder. The actual content will be generated by the AI.
'use client';

import type { Metadata } from 'next';
import { usePathname } from 'next/navigation';
import './globals.css';
import { Header } from '@/components/layout/header';
import { Footer } from '@/components/layout/footer';
import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/lib/utils';

// Metadata cannot be exported from a client component.
// We can define it here and then use it in a server component wrapper if needed,
// but for now, we'll keep it simple as it's not the focus of the change.
// export const metadata: Metadata = {
//   title: 'ScoutFlair',
//   description: 'The future of sports scouting',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hideHeaderFooter = pathname.startsWith('/signup') || pathname.startsWith('/signin');

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>ScoutFlair</title>
        <meta name="description" content="The future of sports scouting" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Lato:wght@400;500;700&family=Manrope:wght@700&family=Merriweather&family=Montserrat:wght@500&family=Poppins:wght@600&family=Roboto:ital,wght@0,500;1,500&display=swap" rel="stylesheet" />
      </head>
      <body className="font-lato antialiased">
        <div className={cn("flex flex-col min-h-screen", { 'bg-[#192B4D]': hideHeaderFooter })}>
          {!hideHeaderFooter && <Header />}
          <main className="flex-grow">{children}</main>
          {!hideHeaderFooter && <Footer />}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
